# Generated by Django 4.2.4 on 2023-08-12 03:31

from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='note',
            field=django_bleach.models.BleachField(default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='precollected_price',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bill',
            name='product_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
