# Generated by Django 4.2.3 on 2023-07-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='id',
        ),
    ]
