# Generated by Django 4.2.4 on 2023-08-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0003_alter_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.CharField(db_index=True, default='ls6HvrORjmA', editable=False, max_length=9, primary_key=True, serialize=False),
        ),
    ]
