# Generated by Django 4.2.3 on 2023-07-26 13:25

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0004_blog_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=django_bleach.models.BleachField(max_length=100),
        ),
    ]
