# Generated by Django 4.2.4 on 2023-08-12 05:35

import api.models.bill
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0005_alter_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.CharField(default=api.models.bill.bill_token, editable=False, max_length=9, primary_key=True, serialize=False),
        ),
    ]
