# Generated by Django 4.2.3 on 2023-08-01 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0005_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='address',
        ),
    ]
