# Generated by Django 4.2.3 on 2023-08-02 13:26

from django.db import migrations, models
import django_bleach.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0006_remove_bill_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='location',
            field=django_bleach.models.BleachField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
