# Generated by Django 4.2.4 on 2023-08-12 14:23

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0006_alter_bill_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='location',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='total',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='bill',
            name='current_location',
            field=django_bleach.models.BleachField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='bill',
            name='product_description',
            field=django_bleach.models.BleachField(default='', max_length=512),
        ),
    ]
