# Generated by Django 4.2.3 on 2023-08-02 13:31

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0007_bill_location_alter_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='location',
            field=django_bleach.models.BleachField(default='Chưa xác định', max_length=255),
        ),
    ]
