# Generated by Django 4.2.4 on 2023-08-16 15:42

import api.models.bill
from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0007_rename_location_bill_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.CharField(default=api.models.bill.bill_token, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='note',
            field=django_bleach.models.BleachField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_price',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
