# Generated by Django 4.2.3 on 2023-08-02 13:43

from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0008_alter_bill_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=django_bleach.models.BleachField(max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
