# Generated by Django 4.2.4 on 2023-08-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0008_alter_bill_id_alter_bill_note_alter_bill_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='delivery_option',
            field=models.CharField(choices=[('nd', 'Nội địa'), ('vt', 'Việt-Trung')], default=None, max_length=2, null=True),
        ),
    ]
